# Basics of Functions Used

Here, we will discuss about the various functions and logics used in the actual code of Bidirectional Lstm + CRF code.

In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

torch.manual_seed(1)

torch.max() function : It gives maximum value from a list of real numbers.

In [8]:
a1 = [4,3,5,6,1,0,7]
a1 = torch.LongTensor(a1)
b1 = torch.max(a1)
print(b1)

a2 = torch.LongTensor([[4,3,5,6],
                       [9,1,0,7]])
b2 = torch.max(a2)
print(b2)

b3 = torch.max(a2,1)   # it is used for getting maximum values row wise and it returns values and their indices. 
print(b3)

tensor(7)
tensor(9)
torch.return_types.max(
values=tensor([6, 9]),
indices=tensor([3, 0]))


In [14]:
a3 = torch.FloatTensor([[1,3,4,2]])
_,idx = torch.max(a3,1)
print(idx)

tensor([2])


In [19]:
def argmax(vec):
  # return the argmax as a python int
  _, idx = torch.max(vec, 1)
  return idx.item()             # this will return index 2 for a3 vector

def log_sum_exp(vec):
  max_score = vec[0, argmax(vec)]  # this signifies 0th row and max index returned by argmax(vec) function
  print(f'max_score : {max_score} Type: {type(max_score)}')
  max_score_broadcast = max_score.view(1, -1).expand(1, vec.size()[1])
  print(f'max_score_broadcast : {max_score_broadcast}')
  return max_score + torch.log(torch.sum(torch.exp(vec - max_score_broadcast)))

print(log_sum_exp(a3))

max_score : 4.0 Type: <class 'torch.Tensor'>
max_score_broadcast : tensor([[4., 4., 4., 4.]])
tensor(4.4402)


Lets see log_sum_exp() in detail:
- max_score will be retuning the max number from vector vec
- Now, let's see about the other part

In [23]:
max_score = torch.FloatTensor([4])
print(type(max_score))

<class 'torch.Tensor'>


In [24]:
print(max_score.view(1, -1))

tensor([[4.]])


In [26]:
max_score_broadcast = max_score.view(1, -1).expand(1, 4)
print(max_score_broadcast)

tensor([[4., 4., 4., 4.]])


In [30]:
np.exp(-3)

0.049787068367863944

In [0]:
a3 = torch.FloatTensor([[1,3,4,2]])

In [27]:
print(torch.exp(a3 - max_score_broadcast))
print(torch.sum(torch.exp(a3 - max_score_broadcast)))
print(torch.log(torch.sum(torch.exp(a3 - max_score_broadcast))))

tensor([[0.0498, 0.3679, 1.0000, 0.1353]])
tensor(1.5530)
tensor(0.4402)
